---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dynamodb
  template:
    metadata:
      labels:
        name: dynamodb
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: dynamodb
        image: deangiberson/aws-dynamodb-local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
